

save_dir: workspace/enhanced_nanodet_640_mobilenext_l
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: mobilenext #ShuffleNetV2
      out_stages: [5,12,18]   #[2,3,4] the medium version , ouput channels: [192,384,576]
      pretrained: True
      activation: ReLU6
    fpn:
      name: GhostPAN
      in_channels: [192,384,960]  #[116, 232, 464]
      out_channels: 160 #96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: Hardswish
      ghost_block_type: plus #todo 增加新的ghost
    head:
      name: NanoDetPlusPlusHead
      conv_type: DWConv 
      num_classes: 80
      input_channel: 160 #96
      feat_channels: 160 #96
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: Hardswish
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 80
      input_channel: 320 #192
      feat_channels: 320
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: Hardswish
      reg_max: 7
data:
  train:
    name: CocoDataset
    img_path: /home/ubuntu/mmdetection/data/coco/train2017
    ann_path:  /home/ubuntu/mmdetection/data/coco/annotations/instances_train2017.json
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      #rotation: 
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: CocoDataset
    img_path:  /home/ubuntu/mmdetection/data/coco/val2017
    ann_path:  /home/ubuntu/mmdetection/data/coco/annotations/instances_val2017.json
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 12  #todo 原来是8
  batchsize_per_gpu: 48 # 96
schedule:
  #sresume:
  #resume: /home/ubuntu/nanodet/workspace/nanodet-plus-m_416_Rep/model_best/model_best.ckpt
  #load_model:
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05  #todo 原来是0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 300
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  val_intervals: 5
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 1000

class_names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
              'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant',
              'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog',
              'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
              'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
              'skis', 'snowboard', 'sports_ball', 'kite', 'baseball_bat',
              'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket',
              'bottle', 'wine_glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
              'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
              'hot_dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
              'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop',
              'mouse', 'remote', 'keyboard', 'cell_phone', 'microwave',
              'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
              'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']
